alb_dns: "tf-asb-flow-ruoxi-test-alb-509373789.us-west-2.elb.amazonaws.com"

ec2_instances:
  a:
    public_ip: "52.24.48.103"
    private_ip: "10.1.1.170"
  b:
    public_ip: "44.248.246.2"
    private_ip: "10.1.2.177"
  c:
    public_ip: "35.160.69.36"
    private_ip: "10.1.3.14"
