---
- name: Intro to Ansible Playbooks
  hosts: web_servers

  tasks:
  - name: Copy file hosts with permissions
    ansible.builtin.copy:
      src: ./cool-file.txt # in my computer
      dest: /tmp/cool-file-backup.txt # <- in all targets!
      mode: '0644'