[web]
a ansible_host=52.24.48.103 ansible_user=ec2-user ansible_ssh_private_key_file=./ruoxi-test-ssh-key.pem
b ansible_host=44.248.246.2 ansible_user=ec2-user ansible_ssh_private_key_file=./ruoxi-test-ssh-key.pem
c ansible_host=35.160.69.36 ansible_user=ec2-user ansible_ssh_private_key_file=./ruoxi-test-ssh-key.pem
